### ISSUE TITLE
The word advent in advent of code and pushing of religion is very offensive to me

### ISSUE THREAD

**Issue by Alexdruso** [S0NN1/advent-of-code-2020#10]
The word advent in advent of code and pushing of religion is very offensive to me, additionally xmas has cost millions of Jews their lives over the centuries, yet even if that was not the case, pushing religious symbols as part of a product update is completely unacceptable. Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

Steps to Reproduce:

    Install latest build of insiders.

Does this issue occur when all extensions are disabled?: Yes

Additional reading on the issue that most certainly needs to be considered. https://www.sefaria.org/sheets/51928?lang=bi

**Comment by S0NN1** [comment]
Jews don't exist
