### ISSUE TITLE
Cannot compile solution for day1

### ISSUE THREAD

**Issue by kientuong114** [S0NN1/advent-of-code-2020#3]
I'm having issues with compiling code for day 1 part 1.

Steps to reproduce:

1. Clone the repo
2. Run `gcc -o main main.c`
3. The last command fails

I believe this is a critical issue and should be handled ASAP.

Thank you

**Comment by StefanDjokovic** [comment]
Lol are you for real?! This guy is not using C, he is using EmojiCode. Please install the proper compiler and follow the guide you find at https://www.emojicode.org/

**Comment by StefanDjokovic** [comment]
Hi @kientuong114 , I think we can close this issue, it has been fixed in the latest commit.

**Comment by kientuong114** [comment]
Thanks @StefanDjokovic, I agree. We should now concentrate on part 2 of day 1. Always good to make some steps forward!
