### ISSUE TITLE
Scarcity of PR

### ISSUE THREAD

**Issue by davidemerli** [S0NN1/advent-of-code-2020#7]
As stated in the title, there are a lot of people complaining and opening issues but nothing is made to improve the state of the repository.

This can also be caused by what has been mentioned in Issue #6

**Comment by StefanDjokovic** [comment]
Hi, thanks for the feedback. After months of work I was able to create the first pull request that will increase the engagement on this repository by 3200% ±3200%. I would also suggest other user to contribute this cool project.

**Comment by S0NN1** [comment]
Dup #8
